# Generated by Django 6.0 on 2026-02-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_alter_cake_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.ImageField(upload_to='cakes/'),
        ),
    ]
